### ISSUE TITLE
Possible typo in Table 1

### ISSUE THREAD

**Issue by matteo-rizzo** [gsalzer/cgt#2]
Hi, and thank you for your work. I'm working on this dataset for ML applications and running experiments on each subset. From my analysis, it seems like the subset SBcurated has 16 labels and not 10 as declared in Table 1 of the paper (you might have swapped the value with the last column by mistake). Thanks!

**Comment by gsalzer** [comment]
The semantics of the `weakness` column in Table 1 is the number of labels according to the original dataset.

SBcurated groups the contracts according to the DASP classification, which consists of 10 labels; therefore the number 10 in the column "weaknesses" in Table 1. In the course of our work, we labeled the contracts also according to the SWC registry, which is more fine-grained than DASP. This results in 16 groups. As label in the consolidated dataset, we then used the more accurate labeling according to SWC.

In Table 11 in the appendix, you find the correspondence between DASP and SWC labels. For the dataset SBcurated, the DASP-category 2 (access control) is broken down into `access_control-105`, `access_control-106`, `access_control-112`, `access_control-115`, `access_control-118`, and `access_control-124`. Likewise, DASP-category 5 (denial of service), is split into `denial_of_service-113` and `denial_of_service-128`. The three-digit numbers correspond to the SWC classification. This adds up to six extra labels.
